Repository obsproject/obs-browser, pull requests merged in 2020-02, with the labels that each got.

#191 Set icon for browser source
  obs-browser-plugin.cpp
Labels: Enhancement

#187 Remove invalid CMake command
  CMakeLists.txt
Labels: Bug Fix

#188 Display errors in browser panels instead of an empty page
  data/error.html
  data/locale/en-US.ini
  panel/browser-panel-client.cpp
  panel/browser-panel-client.hpp
Labels: Bug Fix, Enhancement

#189 Fix CSS injection by using a style element
  browser-client.cpp
Labels: Bug Fix, Seeking Testers

#190 Use monospace font for Custom CSS property
  obs-browser-plugin.cpp
Labels: Enhancement

#193 Unblacklist Intel igpu in single GPU configs
  obs-browser-plugin.cpp
Labels: Bug Fix

#179 Remove unused code
  obs-browser-source.cpp
Labels: Code Cleanup

#162 Size browser panels correctly on Mac HiDPI
  panel/browser-panel.cpp
Labels: Bug Fix, Seeking Testers

#196 Fix compiler error in browser source when shared textures are disabled
  obs-browser-plugin.cpp
Labels: Bug Fix, Code Cleanup, PRIORITY

#186 JS API Enhancements
  README.md
  browser-app.cpp
  browser-client.cpp
  obs-browser-plugin.cpp
  obs-browser-source.cpp
Labels: Code Cleanup, Enhancement

#199 Fix loading local files with a hash in the path
  obs-browser-source.cpp
Labels: Bug Fix

#166 Linux support
  CMakeLists.txt
  FindCEF.cmake
Labels: Enhancement, PRIORITY, Seeking Testers

#203 Fix crash when replay buffer events are triggered
  obs-browser-plugin.cpp
Labels: Bug Fix
