Repository obsproject/obs-browser, pull requests merged in 2021-03, with the labels that each got.

#270 Only use GPU SRGB if source texture supports it
  obs-browser-source.cpp
Labels: Bug Fix

#267 Fix unnecessary pixel ratio calculations on macOS
  panel/browser-panel-internal.hpp
  panel/browser-panel.cpp
Labels: Bug Fix

#233 Update macOS minimum version to 10.13
  CMakeLists.txt
Labels: Seeking Testers

#263 Add missing files check for local browser sources
  obs-browser-plugin.cpp
Labels: Enhancement

#163 Panels: Right click Reload, use Qt context menu
  panel/browser-panel-client.cpp
  panel/browser-panel-client.hpp
Labels: Bug Fix, Code Cleanup, Enhancement

#269 Fix cmake option set
  CMakeLists.txt
Labels: Bug Fix
