Repository obsproject/obs-browser, pull requests merged in 2021-11, with the labels that each got.

#327 obs-browser: Fix compiler warnings
  browser-client.cpp
Labels: Code Cleanup

#323 Add full support for CEF 4638
  browser-app.cpp
  browser-client.cpp
  browser-client.hpp
  browser-scheme.cpp
  browser-scheme.hpp
  cef-headers.hpp
  obs-browser-source.cpp
  obs-browser-source.hpp
  panel/browser-panel.cpp
Labels: Bug Fix

#311 Set window title for web popups using X11 (on Linux)
  panel/browser-panel-client.cpp
Labels: Enhancement

#330 Improve performance of CEF 4638 browser sources
  cef-headers.hpp
  obs-browser-source.cpp
Labels: Bug Fix
