Repository obsproject/obs-browser, pull requests merged in 2022-07, with the labels that each got.

#367 Replace type mismatch with range-based for loop
  panel/browser-panel-client.cpp
Labels: Bug Fix

#366 Back up then restore POSIX signal handlers on CefInitialize
  CMakeLists.txt
  deps/signal-restore.cpp
  deps/signal-restore.hpp
  obs-browser-plugin.cpp
Labels: Bug Fix

#351 Use auto release refs
  browser-client.cpp
  obs-browser-plugin.cpp
  obs-browser-source.hpp
Labels: Code Cleanup

#371 Update clang-format from 12 to 13
  .github/workflows/clang-format.yml
  browser-client.cpp
  formatcode.sh
Labels: Enhancement, Code Cleanup
