Repository obsproject/obs-browser, pull requests merged in 2024-10, with the labels that each got.

#458 cmake: Fix CEF minimum version
  CMakeLists.txt
Labels: Bug Fix, Code Cleanup

#454 Replace obs-websocket-api copy with CMake target
  CMakeLists.txt
  deps/obs-websocket-api/.clang-format
  deps/obs-websocket-api/obs-websocket-api.h
  obs-browser-plugin.cpp
Labels: Code Cleanup

#460 Wait on shutdown for docks to close on Linux (Event-based solution)
  panel/browser-panel-client.cpp
  panel/browser-panel-client.hpp
  panel/browser-panel-internal.hpp
  panel/browser-panel.cpp
Labels: Bug Fix
